_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 12
                - 55
            "2":
                - 12
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
                - 61
            "4": 3.12.8
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size:
    value: 1024
embedding_dim_dir:
    value: 4
embedding_dim_pos:
    value: 10
hf:
    value: 6
hn:
    value: 0.2
layer_sizes:
    value:
        - 84
        - 256
        - 256
        - 256
        - 256
        - 4
learning_rate:
    value: 0.0005
nb_bins:
    value: 192
num_epochs:
    value: 10
num_freqs_dir:
    value: 4
num_freqs_pos:
    value: 10
seed:
    value: 42
